### ISSUE TITLE
Latest build crashes on start with X11

### ISSUE THREAD

**Issue by SUPERCILEX** [pop-os/cosmic-term#126]
```
[2024-02-07T22:23:14Z WARN  wgpu_hal::gles::egl] No config found!
[2024-02-07T22:23:14Z WARN  wgpu_hal::gles::egl] EGL says it can present to the window but not natively
[2024-02-07T22:23:14Z ERROR winit::platform_impl::platform] X11 error: XError {
        description: "BadMatch (invalid parameter attributes)",
        error_code: 8,
        request_code: 149,
        minor_code: 4,
    }
[2024-02-07T22:23:14Z ERROR winit::platform_impl::platform] X11 error: XError {
        description: "BadMatch (invalid parameter attributes)",
        error_code: 8,
        request_code: 149,
        minor_code: 4,
    }
[2024-02-07T22:23:14Z ERROR winit::platform_impl::platform] X11 error: XError {
        description: "BadMatch (invalid parameter attributes)",
        error_code: 8,
        request_code: 149,
        minor_code: 4,
    }
thread 'main' panicked at /build/cosmic-term-LTyHhF/cosmic-term-0.1.0~1707327262~22.04~fec6738/vendor/winit/src/platform_impl/linux/x11/window.rs:1028:18:
Failed to call XMapRaised: XError { description: "BadMatch (invalid parameter attributes)", error_code: 8, request_code: 149, minor_code: 4 }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at /build/cosmic-term-LTyHhF/cosmic-term-0.1.0~1707327262~22.04~fec6738/vendor/winit/src/platform_impl/linux/x11/window.rs:513:34:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
stack backtrace:
   0:     0x57bf6ab1b15c - <unknown>
   1:     0x57bf6ab4ad30 - <unknown>
   2:     0x57bf6ab179af - <unknown>
   3:     0x57bf6ab1af44 - <unknown>
   4:     0x57bf6ab1c887 - <unknown>
   5:     0x57bf6ab1c5ef - <unknown>
   6:     0x57bf6ab1cd08 - <unknown>
   7:     0x57bf6ab1cbee - <unknown>
   8:     0x57bf6ab1b626 - <unknown>
   9:     0x57bf6ab1c952 - <unknown>
  10:     0x57bf69f651b5 - <unknown>
  11:     0x57bf69f656f3 - <unknown>
  12:     0x57bf6a247f03 - <unknown>
  13:     0x57bf6a2380ab - <unknown>
  14:     0x57bf6a07826d - <unknown>
  15:     0x57bf6a06b070 - <unknown>
  16:     0x57bf6a0fad67 - <unknown>
  17:     0x57bf6a0fb659 - <unknown>
  18:     0x57bf6a082b42 - <unknown>
  19:     0x57bf69fd7055 - <unknown>
  20:     0x57bf69fde8b3 - <unknown>
  21:     0x57bf6a058869 - <unknown>
  22:     0x57bf6ab0f817 - <unknown>
  23:     0x57bf6a05885e - <unknown>
  24:     0x747414a29d90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  25:     0x747414a29e40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  26:     0x57bf69f65c65 - <unknown>
  27:                0x0 - <unknown>
thread 'main' panicked at library/core/src/panicking.rs:144:5:
panic in a destructor during cleanup
thread caused non-unwinding panic. aborting.
```

**Comment by SUPERCILEX** [comment]
Actually every single cosmic app seems to crash like this on start now.

**Comment by jackpot51** [comment]
Is it possible you upgraded graphics drivers and need to reboot?

**Comment by SUPERCILEX** [comment]
Nope, this is after a reboot

**Comment by jackpot51** [comment]
What GPU do you have?

**Comment by SUPERCILEX** [comment]
```
~> neofetch
             /////////////                asaveau@pop-os 
         /////////////////////            -------------- 
      ///////*767////////////////         OS: Pop!_OS 22.04 LTS x86_64 
    //////7676767676*//////////////       Host: XPS 17 9700 
   /////76767//7676767//////////////      Kernel: 6.6.10-76060610-generic 
  /////767676///*76767///////////////     Uptime: 2 mins 
 ///////767676///76767.///7676*///////    Packages: 2859 (dpkg) 
/////////767676//76767///767676////////   Shell: nu 0.90.1 
//////////76767676767////76767/////////   Resolution: 3840x4320, 3840x4320 
///////////76767676//////7676//////////   DE: GNOME 42.5 
////////////,7676,///////767///////////   WM: Mutter 
/////////////*7676///////76////////////   WM Theme: Pop 
///////////////7676////////////////////   Theme: Pop [GTK2/3] 
 ///////////////7676///767////////////    Icons: Pop [GTK2/3] 
  //////////////////////'////////////     Terminal: gnome-terminal 
   //////.7676767676767676767,//////      CPU: Intel i7-10875H (16) @ 5.100GHz 
    /////767676767676767676767/////       GPU: NVIDIA GeForce RTX 2060 Max-Q 
      ///////////////////////////         GPU: Intel CometLake-H GT2 [UHD Graphics] 
         /////////////////////            Memory: 4426MiB / 64049MiB 
             /////////////
```

**Comment by SUPERCILEX** [comment]
Fixed itself at some point.
