### ISSUE TITLE
[Bug] Fails to launch if the font is missing

### ISSUE THREAD

**Issue by Elias-Graf** [pop-os/cosmic-term#323]
```
❯ cosmic-term
[2024-09-02T20:07:41Z ERROR cosmic_term] 'Fira Mono' is not in the font list
thread 'main' panicked at src/main.rs:620:69:
index out of bounds: the len is 0 but the index is 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Interestingly enough, the configured font should be Hasklug NF (maybe that got cleared though when upgrading the package).

**Comment by Elias-Graf** [comment]
Ah, ok, not true. I misread, the error is not the panic. See panic here with backtrace:

```
❯ RUST_BACKTRACE=full cosmic-term
[2024-09-02T20:12:33Z ERROR cosmic_term] 'Fira Mono' is not in the font list
thread 'main' panicked at src/main.rs:620:69:
index out of bounds: the len is 0 but the index is 0
stack backtrace:
   0:     0x5566940b15c5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd736fd5964392270
   1:     0x5566940e01fb - core::fmt::write::hc6043626647b98ea
   2:     0x5566940ad00f - std::io::Write::write_fmt::h0d24b3e0473045db
   3:     0x5566940b139e - std::sys_common::backtrace::print::h45eb8174d25a1e76
   4:     0x5566940b2a89 - std::panicking::default_hook::{{closure}}::haf3f0170eb4f3b53
   5:     0x5566940b282a - std::panicking::default_hook::hb5d3b27aa9f6dcda
   6:     0x5566940b2f23 - std::panicking::rust_panic_with_hook::h6b49d59f86ee588c
   7:     0x5566940b2e04 - std::panicking::begin_panic_handler::{{closure}}::hd4c2f7ed79b82b70
   8:     0x5566940b1a89 - std::sys_common::backtrace::__rust_end_short_backtrace::h2946d6d32d7ea1ad
   9:     0x5566940b2b37 - rust_begin_unwind
  10:     0x556692d645c3 - core::panicking::panic_fmt::ha02418e5cd774672
  11:     0x556692d647d7 - core::panicking::panic_bounds_check::hc4af019f20d205d1
  12:     0x556692ec0b68 - cosmic_term::App::set_curr_font_weights_and_stretches::hef57adfd73028dc5
  13:     0x556692ec5fbb - <cosmic_term::App as cosmic::app::Application>::init::h6fdb57dce535e8c0
  14:     0x556692efaaca - <cosmic::executor::single::Executor as iced_futures::executor::Executor>::enter::hcd712441a4a2969e
  15:     0x556692e161a9 - iced_winit::multi_window::run::hf636663658a82c50
  16:     0x556692ee1cc8 - cosmic_term::main::h0611fc07b299ba91
  17:     0x556692d6f4e3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h01f1a13fb46a0214
  18:     0x556692fee739 - std::rt::lang_start::{{closure}}::h0b19452a50dd829f
  19:     0x5566940a44ed - std::rt::lang_start_internal::hcee5ed89fc25829a
  20:     0x556692ee2285 - main
  21:     0x7fc2f52f914e - __libc_start_call_main
  22:     0x7fc2f52f9209 - __libc_start_main@@GLIBC_2.34
  23:     0x556692d650a5 - _start
  24:                0x0 - <unknown>

```

**Comment by Elias-Graf** [comment]
Sadly can't provide version info, since there is no `--version` flag, and the app doesn't launch, so I can't reach the "About" panel for the commit :D

**Comment by MoSal** [comment]
> Sadly can't provide version info, since there is no `--version` flag, and the app doesn't launch, so I can't reach the "About" panel for the commit :D

Does this work?

```
strings /path/to/cosmic-term|grep -E '^git-descriptionhashcosmic-terminal[0-9a-f]+' -o| tail -c -41
```

As for the panic, it's triggered because the monospace font list is empty. Do you have some monospace fonts installed? Note that they have to be not variable.

I will send a PR that detects this and prints an error message.

**Comment by Elias-Graf** [comment]
```
strings $(which cosmic-term) |grep -E '^git-descriptionhashcosmic-terminal[0-9a-f]+' -o| tail -c -41
```
Doesn't output anything, but that could be a nixos thing.

I should have Hasklug NF Mono installed, see Terminal Font:

![image](https://github.com/user-attachments/assets/617a9d71-2453-4d6d-8b93-066759711ee5)

**Comment by Elias-Graf** [comment]
I've now installed "Fira Mono" using:

```nix
{ pkgs, ... }:
{
  fonts.packages = with pkgs; [
    (nerdfonts.override {
      fonts = [
        "FiraMono"
        "CascadiaCode"
        "Hasklig"
      ];
    })
  ];
}
```

I can find it using `fc-list`:

```
❯ fc-list | grep 'Fira Mono'
Fontconfig error: "/etc/fonts/fonts.conf", line 5: not well-formed (invalid token)
Fontconfig error: Cannot load config file from /etc/fonts/fonts.conf
/nix/store/pczgm78xyd3k095s788x6qsddyqnc25g-fira-4.301/share/fonts/opentype/FiraMono-Regular.otf: Fira Mono:style=Regular
/nix/store/pczgm78xyd3k095s788x6qsddyqnc25g-fira-4.301/share/fonts/opentype/FiraMono-Medium.otf: Fira Mono,Fira Mono Medium:style=Medium,Regular
/nix/store/pczgm78xyd3k095s788x6qsddyqnc25g-fira-4.301/share/fonts/opentype/FiraMono-Bold.otf: Fira Mono:style=Bold
```

Still doens't work.

**Comment by MoSal** [comment]
> Fontconfig error: "/etc/fonts/fonts.conf", line 5: not well-formed (invalid token)

Maybe try to fix that error. [fontdb](https://docs.rs/fontdb/latest/fontdb) utilizes [fontconfig_parser](https://docs.rs/fontconfig-parser/latest/fontconfig_parser/) to get a list of font directories, and maybe that's failing.

**Comment by Elias-Graf** [comment]
Looks like that might be the issue. I sadly don't know how to fix that (since the file is generated by nix), but I can revert to the generation before everything broke. Here `fc-list` seems to run fine:

```
❯ fc-list >/dev/null

```

So that's probably also the issue for https://github.com/pop-os/libcosmic/issues/597, with there was some fallback in place though ^^. Especially for libcosmic (or iced or whatever).

**Comment by MoSal** [comment]
> I sadly don't know how to fix that (since the file is generated by nix), but I can revert to the generation before everything broke.

I don't know how things work in Nix, but couldn't you just have edited the file and added quotes around `yes` in line 5?

> wish there was some fallback in place though


The directories that would be scanned if such a backup mechanism was implemented would be:

```
/usr/share/fonts
/usr/local/share/fonts
~/.fonts
~/.local/share/fonts
```

Would that have helped in your case?
Sharing your `/etc/fonts/fonts.conf` would be helpful here.

**Comment by Elias-Graf** [comment]
> I don't know how things work in Nix, but couldn't you just have edited the file and added quotes around yes in line 5?

Sort of. All the files are symlinked in place from the nix store. I would have to find where in the store it resides, unlink the file and copy the actual contents to that location. After testing, I would have to remove the file again, to ensure that the operating system can be generated again, from what is declaratively declared in my nixos configuration file.
If helpful, I think I _could_ do it, yes.

I'm not sure, I'm strongly assuming not. I don't have any of the mentioned directories.

What I meant was, most other applications seem to work fine, except the cosmic apps. They seem to have some font build in.

On the other hand, this is quite the edge case, but it sucks if you can't read any of your operatign system anymore, just because you messed up your font file :D

**Comment by MoSal** [comment]
> I'm not sure, I'm strongly assuming not. I don't have any of the mentioned directories.

That's what I suspected. Still, I think your fallback proposal is sound. So I will send a PR fontdb's way and see what happens.
