### ISSUE TITLE
Crash `attempt to subtract with overflow` when splitting terminal with CTRL + ALT + R

### ISSUE THREAD

**Issue by qarmin** [pop-os/cosmic-term#383]
Commit - fda0850b3b199ff97a6a0f9df6272e7a9e9e419a

```
thread 'main' panicked at /home/rafal/.cargo/git/checkouts/alacritty-d00d61bb8a410914/cacdb5b/alacritty_terminal/src/grid/resize.rs:378:53:
attempt to subtract with overflow
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:662:5
   1: core::panicking::panic_fmt
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panicking.rs:74:14
   2: core::panicking::panic_const::panic_const_sub_overflow
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panicking.rs:181:21
   3: alacritty_terminal::grid::resize::<impl alacritty_terminal::grid::Grid<T>>::shrink_columns
             at /home/rafal/.cargo/git/checkouts/alacritty-d00d61bb8a410914/cacdb5b/alacritty_terminal/src/grid/resize.rs:378:53
   4: alacritty_terminal::grid::resize::<impl alacritty_terminal::grid::Grid<T>>::resize
             at /home/rafal/.cargo/git/checkouts/alacritty-d00d61bb8a410914/cacdb5b/alacritty_terminal/src/grid/resize.rs:30:34
   5: alacritty_terminal::term::Term<T>::resize
             at /home/rafal/.cargo/git/checkouts/alacritty-d00d61bb8a410914/cacdb5b/alacritty_terminal/src/term/mod.rs:677:9
   6: cosmic_term::terminal::Terminal::resize
             at ./src/terminal.rs:392:13
   7: <cosmic_term::terminal_box::TerminalBox<Message> as iced_core::widget::Widget<Message,cosmic::theme::Theme,iced_renderer::fallback::Renderer<iced_wgpu::Renderer,iced_tiny_skia::Renderer>>>::draw
             at ./src/terminal_box.rs:274:9
   8: <iced_widget::column::Column<Message,Theme,Renderer> as iced_core::widget::Widget<Message,Theme,Renderer>>::draw
             at /home/rafal/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/568ff09/iced/widget/src/column.rs:336:17
   9: <cosmic::widget::dnd_destination::DndDestination<Message> as iced_core::widget::Widget<Message,cosmic::theme::Theme,iced_renderer::fallback::Renderer<iced_wgpu::Renderer,iced_tiny_skia::Renderer>>>::draw
             at /home/rafal/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/568ff09/src/widget/dnd_destination.rs:483:9
  10: iced_widget::pane_grid::content::Content<Message,Theme,Renderer>::draw
             at /home/rafal/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/568ff09/iced/widget/src/pane_grid/content.rs:155:13
  11: <iced_widget::pane_grid::PaneGrid<Message,Theme,Renderer> as iced_core::widget::Widget<Message,Theme,Renderer>>::draw
             at /home/rafal/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/568ff09/iced/widget/src/pane_grid.rs:795:21
  12: <iced_core::element::Map<A,B,Theme,Renderer> as iced_core::widget::Widget<B,Theme,Renderer>>::draw
             at /home/rafal/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/568ff09/iced/core/src/element.rs:384:9
  13: <iced_widget::container::Container<Message,Theme,Renderer> as iced_core::widget::Widget<Message,Theme,Renderer>>::draw
             at /home/rafal/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/568ff09/iced/widget/src/container.rs:349:13
  14: <iced_widget::row::Row<Message,Theme,Renderer> as iced_core::widget::Widget<Message,Theme,Renderer>>::draw
             at /home/rafal/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/568ff09/iced/widget/src/row.rs:332:17
  15: <iced_widget::column::Column<Message,Theme,Renderer> as iced_core::widget::Widget<Message,Theme,Renderer>>::draw
             at /home/rafal/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/568ff09/iced/widget/src/column.rs:336:17
  16: <iced_widget::column::Column<Message,Theme,Renderer> as iced_core::widget::Widget<Message,Theme,Renderer>>::draw
             at /home/rafal/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/568ff09/iced/widget/src/column.rs:336:17
  17: <iced_widget::container::Container<Message,Theme,Renderer> as iced_core::widget::Widget<Message,Theme,Renderer>>::draw
             at /home/rafal/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/568ff09/iced/widget/src/container.rs:349:13
  18: <cosmic::widget::popover::Popover<Message,Renderer> as iced_core::widget::Widget<Message,cosmic::theme::Theme,Renderer>>::draw
             at /home/rafal/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/568ff09/src/widget/popover.rs:201:9
  19: iced_runtime::user_interface::UserInterface<Message,Theme,Renderer>::draw
             at /home/rafal/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/568ff09/iced/runtime/src/user_interface.rs:501:9
  20: iced_winit::program::run_instance::{{closure}}
             at /home/rafal/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/568ff09/iced/winit/src/program.rs:1703:25
  21: iced_winit::program::run::Runner<Message,F,C>::process_event
             at /home/rafal/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/568ff09/iced/winit/src/program.rs:447:28
  22: <iced_winit::program::run::Runner<Message,F,C> as winit::application::ApplicationHandler>::about_to_wait
             at /home/rafal/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/568ff09/iced/winit/src/program.rs:347:13
  23: <&mut A as winit::application::ApplicationHandler>::about_to_wait
             at /home/rafal/.cargo/git/checkouts/winit-40d7deb2b0c08730/1cc02bd/src/application.rs:374:9
  24: <&mut A as winit::application::ApplicationHandler>::about_to_wait
             at /home/rafal/.cargo/git/checkouts/winit-40d7deb2b0c08730/1cc02bd/src/application.rs:374:9
  25: winit::platform_impl::linux::x11::EventLoop::single_iteration
             at /home/rafal/.cargo/git/checkouts/winit-40d7deb2b0c08730/1cc02bd/src/platform_impl/linux/x11/mod.rs:568:9
  26: winit::platform_impl::linux::x11::EventLoop::poll_events_with_timeout
             at /home/rafal/.cargo/git/checkouts/winit-40d7deb2b0c08730/1cc02bd/src/platform_impl/linux/x11/mod.rs:507:9
  27: winit::platform_impl::linux::x11::EventLoop::pump_app_events
             at /home/rafal/.cargo/git/checkouts/winit-40d7deb2b0c08730/1cc02bd/src/platform_impl/linux/x11/mod.rs:426:13
  28: winit::platform_impl::linux::x11::EventLoop::run_app_on_demand
             at /home/rafal/.cargo/git/checkouts/winit-40d7deb2b0c08730/1cc02bd/src/platform_impl/linux/x11/mod.rs:385:19
  29: winit::platform_impl::linux::x11::EventLoop::run_app
             at /home/rafal/.cargo/git/checkouts/winit-40d7deb2b0c08730/1cc02bd/src/platform_impl/linux/x11/mod.rs:376:9
  30: winit::platform_impl::linux::EventLoop::run_app
             at /home/rafal/.cargo/git/checkouts/winit-40d7deb2b0c08730/1cc02bd/src/platform_impl/linux/mod.rs:427:56
  31: winit::event_loop::EventLoop::run_app
             at /home/rafal/.cargo/git/checkouts/winit-40d7deb2b0c08730/1cc02bd/src/event_loop.rs:228:9
  32: iced_winit::program::run
             at /home/rafal/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/568ff09/iced/winit/src/program.rs:626:17
  33: iced::program::Program::run_with
             at /home/rafal/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/568ff09/iced/src/program.rs:183:12
  34: cosmic::app::multi_window::MultiWindow<P>::run_with
             at /home/rafal/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/568ff09/src/app/multi_window.rs:124:9
  35: cosmic::app::run
             at /home/rafal/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/568ff09/src/app/mod.rs:179:9
  36: cosmic_term::main
             at ./src/main.rs:168:5
  37: core::ops::function::FnOnce::call_once
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'PTY reader' panicked at /home/rafal/.cargo/git/checkouts/alacritty-d00d61bb8a410914/cacdb5b/alacritty_terminal/src/grid/mod.rs:439:30:
index out of bounds: the len is 0 but the index is 0
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:662:5
   1: core::panicking::panic_fmt
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panicking.rs:74:14
   2: core::panicking::panic_bounds_check
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panicking.rs:276:5
   3: <usize as core::slice::index::SliceIndex<[T]>>::index_mut
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/slice/index.rs:308:14
   4: core::slice::index::<impl core::ops::index::IndexMut<I> for [T]>::index_mut
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/slice/index.rs:27:9
   5: <alloc::vec::Vec<T,A> as core::ops::index::IndexMut<I>>::index_mut
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/alloc/src/vec/mod.rs:2932:9
   6: <alacritty_terminal::grid::row::Row<T> as core::ops::index::IndexMut<alacritty_terminal::index::Column>>::index_mut
             at /home/rafal/.cargo/git/checkouts/alacritty-d00d61bb8a410914/cacdb5b/alacritty_terminal/src/grid/row.rs:210:24
   7: alacritty_terminal::grid::Grid<T>::cursor_cell
             at /home/rafal/.cargo/git/checkouts/alacritty-d00d61bb8a410914/cacdb5b/alacritty_terminal/src/grid/mod.rs:439:30
   8: alacritty_terminal::term::Term<T>::write_at_cursor
             at /home/rafal/.cargo/git/checkouts/alacritty-d00d61bb8a410914/cacdb5b/alacritty_terminal/src/term/mod.rs:986:31
   9: <alacritty_terminal::term::Term<T> as vte::ansi::Handler>::input
             at /home/rafal/.cargo/git/checkouts/alacritty-d00d61bb8a410914/cacdb5b/alacritty_terminal/src/term/mod.rs:1100:13
  10: <vte::ansi::Performer<H,T> as vte::Perform>::print
             at /home/rafal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/vte-0.13.0/src/ansi.rs:1205:9
  11: vte::Parser<_>::perform_action
             at /home/rafal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/vte-0.13.0/src/lib.rs:237:30
  12: vte::Parser<_>::perform_state_change
             at /home/rafal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/vte-0.13.0/src/lib.rs:180:17
  13: vte::Parser<_>::advance
             at /home/rafal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/vte-0.13.0/src/lib.rs:148:9
  14: vte::ansi::Processor<T>::advance
             at /home/rafal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/vte-0.13.0/src/ansi.rs:314:13
  15: alacritty_terminal::event_loop::EventLoop<T,U>::pty_read
             at /home/rafal/.cargo/git/checkouts/alacritty-d00d61bb8a410914/cacdb5b/alacritty_terminal/src/event_loop.rs:155:17
  16: alacritty_terminal::event_loop::EventLoop<T,U>::spawn::{{closure}}
             at /home/rafal/.cargo/git/checkouts/alacritty-d00d61bb8a410914/cacdb5b/alacritty_terminal/src/event_loop.rs:285:51
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

https://github.com/user-attachments/assets/a8da03d6-ab42-4b38-b0a4-5fb8d283098e

Steps to reproduce
- open terminal
- click multiple times CTRL + ALT + R

**Comment by qarmin** [comment]
Similar crash with CTRL + ALT + D
```
thread 'main' panicked at /home/rafal/.cargo/git/checkouts/alacritty-d00d61bb8a410914/cacdb5b/alacritty_terminal/src/term/mod.rs:258:19:
index out of bounds: the len is 0 but the index is 18446744073709551615
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:662:5
   1: core::panicking::panic_fmt
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panicking.rs:74:14
   2: core::panicking::panic_bounds_check
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panicking.rs:276:5
   3: <usize as core::slice::index::SliceIndex<[T]>>::index_mut
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/slice/index.rs:308:14
   4: core::slice::index::<impl core::ops::index::IndexMut<I> for [T]>::index_mut
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/slice/index.rs:27:9
   5: <alloc::vec::Vec<T,A> as core::ops::index::IndexMut<I>>::index_mut
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/alloc/src/vec/mod.rs:2932:9
   6: alacritty_terminal::term::TermDamageState::damage_line
             at /home/rafal/.cargo/git/checkouts/alacritty-d00d61bb8a410914/cacdb5b/alacritty_terminal/src/term/mod.rs:258:19
   7: alacritty_terminal::term::TermDamageState::damage_point
             at /home/rafal/.cargo/git/checkouts/alacritty-d00d61bb8a410914/cacdb5b/alacritty_terminal/src/term/mod.rs:252:9
   8: alacritty_terminal::term::Term<T>::damage
             at /home/rafal/.cargo/git/checkouts/alacritty-d00d61bb8a410914/cacdb5b/alacritty_terminal/src/term/mod.rs:476:13
   9: cosmic_term::terminal::Terminal::update
             at ./src/terminal.rs:680:23
  10: <cosmic_term::terminal_box::TerminalBox<Message> as iced_core::widget::Widget<Message,cosmic::theme::Theme,iced_renderer::fallback::Renderer<iced_wgpu::Renderer,iced_tiny_skia::Renderer>>>::layout
             at ./src/terminal_box.rs:177:13
  11: iced_core::layout::flex::resolve
             at /home/rafal/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/568ff09/iced/core/src/layout/flex.rs:171:17
  12: <iced_widget::column::Column<Message,Theme,Renderer> as iced_core::widget::Widget<Message,Theme,Renderer>>::layout
             at /home/rafal/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/568ff09/iced/widget/src/column.rs:227:9
  13: <cosmic::widget::dnd_destination::DndDestination<Message> as iced_core::widget::Widget<Message,cosmic::theme::Theme,iced_renderer::fallback::Renderer<iced_wgpu::Renderer,iced_tiny_skia::Renderer>>>::layout
             at /home/rafal/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/568ff09/src/widget/dnd_destination.rs:275:9
  14: iced_widget::pane_grid::content::Content<Message,Theme,Renderer>::layout
             at /home/rafal/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/568ff09/iced/widget/src/pane_grid/content.rs:204:13
  15: <iced_widget::pane_grid::PaneGrid<Message,Theme,Renderer> as iced_core::widget::Widget<Message,Theme,Renderer>>::layout::{{closure}}
             at /home/rafal/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/568ff09/iced/widget/src/pane_grid.rs:366:28
  16: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/ops/function.rs:294:13
  17: core::iter::traits::iterator::Iterator::find_map::check::{{closure}}
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/iter/traits/iterator.rs:2902:32
  18: core::iter::traits::iterator::Iterator::try_fold
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/iter/traits/iterator.rs:2405:21
  19: core::iter::traits::iterator::Iterator::find_map
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/iter/traits/iterator.rs:2908:9
  20: <core::iter::adapters::filter_map::FilterMap<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/iter/adapters/filter_map.rs:65:9
  21: alloc::vec::Vec<T,A>::extend_desugared
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/alloc/src/vec/mod.rs:3089:35
  22: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/alloc/src/vec/spec_extend.rs:17:9
  23: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/alloc/src/vec/spec_from_iter_nested.rs:41:9
  24: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/alloc/src/vec/spec_from_iter.rs:33:9
  25: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/alloc/src/vec/mod.rs:2985:9
  26: core::iter::traits::iterator::Iterator::collect
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/iter/traits/iterator.rs:2000:9
  27: <iced_widget::pane_grid::PaneGrid<Message,Theme,Renderer> as iced_core::widget::Widget<Message,Theme,Renderer>>::layout
             at /home/rafal/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/568ff09/iced/widget/src/pane_grid.rs:358:24
  28: <iced_core::element::Map<A,B,Theme,Renderer> as iced_core::widget::Widget<B,Theme,Renderer>>::layout
             at /home/rafal/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/568ff09/iced/core/src/element.rs:331:9
  29: <iced_widget::container::Container<Message,Theme,Renderer> as iced_core::widget::Widget<Message,Theme,Renderer>>::layout::{{closure}}
             at /home/rafal/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/568ff09/iced/widget/src/container.rs:268:22
  30: iced_widget::container::layout::{{closure}}
             at /home/rafal/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/568ff09/iced/widget/src/container.rs:463:18
  31: iced_core::layout::positioned
             at /home/rafal/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/568ff09/iced/core/src/layout.rs:179:19
  32: iced_widget::container::layout
             at /home/rafal/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/568ff09/iced/widget/src/container.rs:458:5
  33: <iced_widget::container::Container<Message,Theme,Renderer> as iced_core::widget::Widget<Message,Theme,Renderer>>::layout
             at /home/rafal/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/568ff09/iced/widget/src/container.rs:259:9
  34: iced_core::layout::flex::resolve
             at /home/rafal/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/568ff09/iced/core/src/layout/flex.rs:171:17
  35: <iced_widget::row::Row<Message,Theme,Renderer> as iced_core::widget::Widget<Message,Theme,Renderer>>::layout
             at /home/rafal/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/568ff09/iced/widget/src/row.rs:223:9
  36: iced_core::layout::flex::resolve
             at /home/rafal/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/568ff09/iced/core/src/layout/flex.rs:171:17
  37: <iced_widget::column::Column<Message,Theme,Renderer> as iced_core::widget::Widget<Message,Theme,Renderer>>::layout
             at /home/rafal/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/568ff09/iced/widget/src/column.rs:227:9
  38: iced_core::layout::flex::resolve
             at /home/rafal/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/568ff09/iced/core/src/layout/flex.rs:171:17
  39: <iced_widget::column::Column<Message,Theme,Renderer> as iced_core::widget::Widget<Message,Theme,Renderer>>::layout
             at /home/rafal/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/568ff09/iced/widget/src/column.rs:227:9
  40: <iced_widget::container::Container<Message,Theme,Renderer> as iced_core::widget::Widget<Message,Theme,Renderer>>::layout::{{closure}}
             at /home/rafal/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/568ff09/iced/widget/src/container.rs:268:22
  41: iced_widget::container::layout::{{closure}}
             at /home/rafal/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/568ff09/iced/widget/src/container.rs:463:18
  42: iced_core::layout::positioned
             at /home/rafal/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/568ff09/iced/core/src/layout.rs:179:19
  43: iced_widget::container::layout
             at /home/rafal/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/568ff09/iced/widget/src/container.rs:458:5
  44: <iced_widget::container::Container<Message,Theme,Renderer> as iced_core::widget::Widget<Message,Theme,Renderer>>::layout
             at /home/rafal/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/568ff09/iced/widget/src/container.rs:259:9
  45: <cosmic::widget::popover::Popover<Message,Renderer> as iced_core::widget::Widget<Message,cosmic::theme::Theme,Renderer>>::layout
             at /home/rafal/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/568ff09/src/widget/popover.rs:118:9
  46: iced_runtime::user_interface::UserInterface<Message,Theme,Renderer>::build
             at /home/rafal/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/568ff09/iced/runtime/src/user_interface.rs:107:20
  47: iced_winit::program::build_user_interface
             at /home/rafal/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/568ff09/iced/winit/src/program.rs:1864:26
  48: iced_winit::program::build_user_interfaces::{{closure}}
             at /home/rafal/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/568ff09/iced/winit/src/program.rs:2316:29
  49: core::iter::adapters::filter_map::filter_map_fold::{{closure}}
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/iter/adapters/filter_map.rs:40:28
  50: core::iter::traits::iterator::Iterator::fold
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/iter/traits/iterator.rs:2583:21
  51: <hashbrown::map::Drain<K,V,A> as core::iter::traits::iterator::Iterator>::fold
             at /rust/deps/hashbrown-0.14.5/src/map.rs:4965:9
  52: <std::collections::hash::map::Drain<K,V> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/collections/hash/map.rs:2564:19
  53: <core::iter::adapters::filter_map::FilterMap<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/iter/adapters/filter_map.rs:149:9
  54: core::iter::traits::iterator::Iterator::for_each
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/iter/traits/iterator.rs:813:9
  55: <hashbrown::map::HashMap<K,V,S,A> as core::iter::traits::collect::Extend<(K,V)>>::extend
             at /rust/deps/hashbrown-0.14.5/src/map.rs:6511:9
  56: <std::collections::hash::map::HashMap<K,V,S> as core::iter::traits::collect::Extend<(K,V)>>::extend
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/collections/hash/map.rs:3142:9
  57: <std::collections::hash::map::HashMap<K,V,S> as core::iter::traits::collect::FromIterator<(K,V)>>::from_iter
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/collections/hash/map.rs:3127:13
  58: core::iter::traits::iterator::Iterator::collect
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/iter/traits/iterator.rs:2000:9
  59: iced_winit::program::build_user_interfaces
             at /home/rafal/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/568ff09/iced/winit/src/program.rs:2312:5
  60: iced_winit::program::run_instance::{{closure}}
             at /home/rafal/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/568ff09/iced/winit/src/program.rs:1660:57
  61: iced_winit::program::run::Runner<Message,F,C>::process_event
             at /home/rafal/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/568ff09/iced/winit/src/program.rs:447:28
  62: <iced_winit::program::run::Runner<Message,F,C> as winit::application::ApplicationHandler>::about_to_wait
             at /home/rafal/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/568ff09/iced/winit/src/program.rs:347:13
  63: <&mut A as winit::application::ApplicationHandler>::about_to_wait
             at /home/rafal/.cargo/git/checkouts/winit-40d7deb2b0c08730/1cc02bd/src/application.rs:374:9
  64: <&mut A as winit::application::ApplicationHandler>::about_to_wait
             at /home/rafal/.cargo/git/checkouts/winit-40d7deb2b0c08730/1cc02bd/src/application.rs:374:9
  65: winit::platform_impl::linux::x11::EventLoop::single_iteration
             at /home/rafal/.cargo/git/checkouts/winit-40d7deb2b0c08730/1cc02bd/src/platform_impl/linux/x11/mod.rs:568:9
  66: winit::platform_impl::linux::x11::EventLoop::poll_events_with_timeout
             at /home/rafal/.cargo/git/checkouts/winit-40d7deb2b0c08730/1cc02bd/src/platform_impl/linux/x11/mod.rs:507:9
  67: winit::platform_impl::linux::x11::EventLoop::pump_app_events
             at /home/rafal/.cargo/git/checkouts/winit-40d7deb2b0c08730/1cc02bd/src/platform_impl/linux/x11/mod.rs:426:13
  68: winit::platform_impl::linux::x11::EventLoop::run_app_on_demand
             at /home/rafal/.cargo/git/checkouts/winit-40d7deb2b0c08730/1cc02bd/src/platform_impl/linux/x11/mod.rs:385:19
  69: winit::platform_impl::linux::x11::EventLoop::run_app
             at /home/rafal/.cargo/git/checkouts/winit-40d7deb2b0c08730/1cc02bd/src/platform_impl/linux/x11/mod.rs:376:9
  70: winit::platform_impl::linux::EventLoop::run_app
             at /home/rafal/.cargo/git/checkouts/winit-40d7deb2b0c08730/1cc02bd/src/platform_impl/linux/mod.rs:427:56
  71: winit::event_loop::EventLoop::run_app
             at /home/rafal/.cargo/git/checkouts/winit-40d7deb2b0c08730/1cc02bd/src/event_loop.rs:228:9
  72: iced_winit::program::run
             at /home/rafal/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/568ff09/iced/winit/src/program.rs:626:17
  73: iced::program::Program::run_with
             at /home/rafal/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/568ff09/iced/src/program.rs:183:12
  74: cosmic::app::multi_window::MultiWindow<P>::run_with
             at /home/rafal/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/568ff09/src/app/multi_window.rs:124:9
  75: cosmic::app::run
             at /home/rafal/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/568ff09/src/app/mod.rs:179:9
  76: cosmic_term::main
             at ./src/main.rs:168:5
  77: core::ops::function::FnOnce::call_once
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

**Comment by leb-kuchen** [comment]
I think the Size methods should be changed to return a minimum of 1. But how alacritty_terminal handles overflow is also completely unpredictable.
