### ISSUE TITLE
Panic on Thelio Major (Pop!_OS Gnome) system

### ISSUE THREAD

**Issue by bbarker** [pop-os/cosmic-term#57]
bbarker@pop-os-thelio-major:~/workspace/cosmic-term$ [2024-01-16T19:47:41Z WARN  wgpu_hal::gles::egl] No config found!
[2024-01-16T19:47:41Z WARN  wgpu_hal::gles::egl] EGL says it can present to the window but not natively
[2024-01-16T19:47:41Z ERROR winit::platform_impl::platform] X11 error: XError {
        description: "BadMatch (invalid parameter attributes)",
        error_code: 8,
        request_code: 149,
        minor_code: 4,
    }
[2024-01-16T19:47:41Z ERROR winit::platform_impl::platform] X11 error: XError {
        description: "BadMatch (invalid parameter attributes)",
        error_code: 8,
        request_code: 149,
        minor_code: 4,
    }
[2024-01-16T19:47:41Z ERROR winit::platform_impl::platform] X11 error: XError {
        description: "BadMatch (invalid parameter attributes)",
        error_code: 8,
        request_code: 149,
        minor_code: 4,
    }
thread 'main' panicked at /home/bbarker/.cargo/git/checkouts/winit-40d7deb2b0c08730/c6ad672/src/platform_impl/linux/x11/window.rs:1028:18:
Failed to call XMapRaised: XError { description: "BadMatch (invalid parameter attributes)", error_code: 8, request_code: 149, minor_code: 4 }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at /home/bbarker/.cargo/git/checkouts/winit-40d7deb2b0c08730/c6ad672/src/platform_impl/linux/x11/window.rs:513:34:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
stack backtrace:
   0:     0x5d4277e8b29c - std::backtrace_rs::backtrace::libunwind::trace::ha637c64ce894333a
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x5d4277e8b29c - std::backtrace_rs::backtrace::trace_unsynchronized::h47f62dea28e0c88d
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5d4277e8b29c - std::sys_common::backtrace::_print_fmt::h9eef0abe20ede486
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x5d4277e8b29c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hed7f999df88cc644
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x5d4277ebadf0 - core::fmt::rt::Argument::fmt::h1539a9308b8d058d
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/fmt/rt.rs:142:9
   5:     0x5d4277ebadf0 - core::fmt::write::h3a39390d8560d9c9
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/fmt/mod.rs:1120:17
   6:     0x5d4277e87aef - std::io::Write::write_fmt::h5fc9997dfe05f882
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/io/mod.rs:1762:15
   7:     0x5d4277e8b084 - std::sys_common::backtrace::_print::h894006fb5c6f3d45
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x5d4277e8b084 - std::sys_common::backtrace::print::h23a2d212c6fff936
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x5d4277e8c9c7 - std::panicking::default_hook::{{closure}}::h8a1d2ee00185001a
  10:     0x5d4277e8c72f - std::panicking::default_hook::h6038f2eba384e475
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:292:9
  11:     0x5d4277e8ce48 - std::panicking::rust_panic_with_hook::h2b5517d590cab22e
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:779:13
  12:     0x5d4277e8cd2e - std::panicking::begin_panic_handler::{{closure}}::h233112c06e0ef43e
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:657:13
  13:     0x5d4277e8b766 - std::sys_common::backtrace::__rust_end_short_backtrace::h6e893f24d7ebbff8
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:170:18
  14:     0x5d4277e8ca92 - rust_begin_unwind
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
  15:     0x5d42772ee2d5 - core::panicking::panic_fmt::hbf0e066aabfa482c
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
  16:     0x5d42772ee813 - core::result::unwrap_failed::hddb4fea594200c52
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/result.rs:1653:5
  17:     0x5d42775a0ca3 - winit::platform_impl::platform::x11::window::UnownedWindow::shared_state_lock::hfeca5465aa45b1e9
  18:     0x5d4277590e6b - <winit::window::Window as core::ops::drop::Drop>::drop::ha6374fbbeda26478
  19:     0x5d427741aead - core::ptr::drop_in_place<winit::window::Window>::h38a2c8fb35b75d4f
  20:     0x5d427740a53c - iced_winit::application::run::{{closure}}::ha0ea0ded7c87f061
  21:     0x5d4277314637 - winit::platform_impl::platform::x11::EventLoop<T>::run_return::single_iteration::h50a0b41e59efd4a8
  22:     0x5d4277314f3b - winit::platform_impl::platform::x11::EventLoop<T>::run_return::h96fbed7b4de421e5
  23:     0x5d4277324a27 - iced_winit::application::run::h15e3ae1aafc94bae
  24:     0x5d42773b42f7 - cosmic::app::run::h5cce4c2b13feab7e
  25:     0x5d4277408eba - cosmic_term::main::h26e0456ad3e28dc1
  26:     0x5d4277427653 - std::sys_common::backtrace::__rust_begin_short_backtrace::h776b846c1ab9294e
  27:     0x5d42773da579 - std::rt::lang_start::{{closure}}::h53d95d8cd470707d
  28:     0x5d4277e7fa17 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hd95060ecd5e1ca24
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:284:13
  29:     0x5d4277e7fa17 - std::panicking::try::do_call::h6e8cf51db32a6e4b
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40
  30:     0x5d4277e7fa17 - std::panicking::try::h3a52eefe24fe3c29
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19
  31:     0x5d4277e7fa17 - std::panic::catch_unwind::h24c28c23c02c3841
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14
  32:     0x5d4277e7fa17 - std::rt::lang_start_internal::{{closure}}::h705d3c9cbc06ef47
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:148:48
  33:     0x5d4277e7fa17 - std::panicking::try::do_call::ha21f52ba13158470
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40
  34:     0x5d4277e7fa17 - std::panicking::try::h5581346bf6aeb1f8
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19
  35:     0x5d4277e7fa17 - std::panic::catch_unwind::h7919645a6b72e25b
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14
  36:     0x5d4277e7fa17 - std::rt::lang_start_internal::h12de51168669836e
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:148:20
  37:     0x5d42773da56e - std::rt::lang_start::h4cf55d11cb2904bb
  38:     0x76eb8be29d90 - <unknown>
  39:     0x76eb8be29e40 - __libc_start_main
  40:     0x5d42772eed85 - _start
  41:                0x0 - <unknown>
thread 'main' panicked at library/core/src/panicking.rs:144:5:
panic in a destructor during cleanup
thread caused non-unwinding panic. aborting.

**Comment by WatchMkr** [comment]
Is this still present?

**Comment by bbarker** [comment]
I switched to xmonad, but still get a related issue. Actually, I had to make a change to flake.nix to even build it - so I'll open up an MR for that:

```
bbarker@pop-os-thelio-major:~/workspace/cosmic-term$ [2024-05-25T16:41:51Z WARN  wgpu_hal::vulkan::instance] Unable to find extension: VK_KHR_surface
[2024-05-25T16:41:51Z WARN  wgpu_hal::vulkan::instance] Unable to find extension: VK_KHR_xlib_surface
[2024-05-25T16:41:51Z WARN  wgpu_hal::vulkan::instance] Unable to find extension: VK_KHR_xcb_surface
[2024-05-25T16:41:51Z WARN  wgpu_hal::vulkan::instance] Unable to find extension: VK_KHR_wayland_surface
[2024-05-25T16:41:51Z WARN  wgpu_hal::vulkan::instance] Unable to find extension: VK_EXT_swapchain_colorspace
[2024-05-25T16:41:51Z WARN  wgpu_hal::vulkan::instance] Unable to find extension: VK_KHR_get_physical_device_properties2
[2024-05-25T16:41:51Z WARN  wgpu_hal::vulkan::instance] InstanceFlags::VALIDATION requested, but unable to find layer: VK_LAYER_KHRONOS_validation
libEGL warning: DRI3: Screen seems not DRI3 capable
libEGL warning: DRI2: failed to authenticate
libEGL warning: DRI3: Screen seems not DRI3 capable
libEGL warning: MESA-LOADER: failed to open zink: /run/opengl-driver/lib/dri/zink_dri.so: cannot open shared object file: No such file or directory (search paths /run/opengl-driver/lib/dri, suffix _dri)

libEGL warning: MESA-LOADER: failed to open swrast: /run/opengl-driver/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /run/opengl-driver/lib/dri, suffix _dri)

[2024-05-25T16:41:51Z ERROR wgpu_hal::gles::egl] EGL 'eglInitialize' code 0x3001: eglInitialize
thread 'main' panicked at /home/bbarker/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/f493634/iced/tiny_skia/src/window/compositor.rs:56:10:
Create softbuffer surface for window: PlatformError(Some("Visual 0x23 does not use softbuffer's pixel format and is unsupported"), None)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by iamkartiknayak** [comment]
Has it been fixed?
